CREATE DATABASE IF NOT EXISTS usermgmt;
USE usermgmt;
CREATE TABLE IF NOT EXISTS users ( 
id INT AUTO_INCREMENT PRIMARY KEY, 
name VARCHAR(150) NOT NULL, 
email VARCHAR(255) NOT NULL UNIQUE, 
role VARCHAR(50) DEFAULT 'user' 
);
